# Generated by Django 2.2.10 on 2021-02-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_for_task_round',
        ),
    ]
