# Generated by Django 2.2.10 on 2021-02-04 19:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0007_auto_20210205_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
