# Generated by Django 2.2.10 on 2021-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0010_remove_profile_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='discord_link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
